model:
  encoder_architecture: "default_heavy"
  model_input_dims: [480, 320]
  only_train_encoder: False
  n_context: 0

training:
  epochs: 400
  initial_epoch: 0
  batch_size: 32
  verbose: 0
  from_checkpoint: False # < when starting training from checkpoint
  from_model: False # < when loading an existing model
  load_checkpoint:
    initial_epoch: 0
    timestamp: "" 
    encoder_only: False # < when only loading the encoder
    verbose: True
  load_model:
    timestamp: ""
    filepath: "models"
    encoder_only: False # < when only loading the encoder
    verbose: True

categories:
  ball:
    object_size: 0.175
    object_height: 0.05
    n_classes: 1
    n_candidates: 5
  penaltyMark:
    object_size: 0.175
    object_height: 0.0
    n_classes: 1
    n_candidates: 5
  # field:
  #   object_size: 0.2
  #   n_classes: 1 # penalty mark, center mark, X intersection, L intersection, T intersection, goal post
  #   n_candidates: 7
  # player:
  #   object_size: 0.5
  #   n_classes: 1

callbacks:
  reduce_lr:
    monitor: "val_total_loss"
    mode: "min"
    factor: 0.2
    patience: 40
    min_lr: 0.0
  early_stopping:
    monitor: "val_total_loss"
    mode: "min"
    patience: 40
  log_dir: "logs/fit/"
  checkpoint_dir: "checkpoints/"

data:
  train_path: "data/tfrecords/train_ds*.tfrecords"
  val_path: "data/tfrecords/val_ds*.tfrecords"